export enum RuleSetComparator {
  AND = 'AND',
  OR = 'OR'
}

export enum RuleConditions {
  EQUALS='EQUALS',
  NOT_EQUALS='NOT_EQUALS',
  GREATER_THAN='GREATER_THAN',
  LESS_THAN='LESS_THAN',
  LIKE='LIKE',
  STARTS_WITH='STARTS_WITH',
  ENDS_WITH='ENDS_WITH',
  CONTAINS='CONTAINS',
  IS_NULL='IS_NULL',
  NOT_NULL='NOT_NULL'
}
